### ISSUE TITLE
[panel.sh] typo in textwidth name for guix

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#1117]
https://github.com/herbstluftwm/herbstluftwm/blob/299b6d54ed46f1ec7d9d0f14dc2c54c0611bb18c/share/panel.sh#L33-L34

I guess it should be `xft` but I’m not a guixer so can’t be sure. @samtinel could you fix it please? (asking you coz you were the one to [add it](https://github.com/herbstluftwm/herbstluftwm/commit/8c78994ae73c3371cb9598bced8735c8a1ebf14e) & so you should know)

**Comment by samtinel** [comment]
Thank you for @ing me, that really looks like a typo! Guess I have manually typed that in back then.
As soon as the replacement part for my currently broken laptop  arrives I will check and make sure, so that might take a few days.

Am 6. Januar 2021 13:54:36 MEZ schrieb "Bohdan Potměkleč" <notifications@github.com>:

**Comment by t-wissmann** [comment]
Of course, the content of the $textwidth variable should match the string that was passed to `which`; so I've fixed this in #1119. Thanks for reporting, @tiosgz!
