### ISSUE TITLE
minimize shortcut without an un-minimize counterpart

### ISSUE THREAD

**Issue by apm256** [herbstluftwm/herbstluftwm#1133]
A suggestion about the following shortcut in `autostart`:

```
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
```

It may be confusing to expose such a shortcut with no obvious way to restore the hidden window.

Either it can be commented by default, or something like this could be offered:

```
# restore all minimized windows of the focused tag
hc keybind $Mod-m foreach CLIENT clients. \
     sprintf MINATT "%c.minimized" CLIENT \
     sprintf TAGATT "%c.tag" CLIENT and \
       , compare MINATT "=" "true" \
       , substitute FOCUS "tags.focus.name" compare TAGATT "=" FOCUS \
       , set_attr MINATT false \
```

It is also possible to propose the minimization feature in a toggle-like way:

```
# toggle: minimize the current window / restore all minimized windows of the focused tag
hc keybind $Mod-m mktemp bool ISMINATT chain \
  . set_attr ISMINATT false \
  . foreach CLIENT clients. \
      sprintf MINATT "%c.minimized" CLIENT \
      sprintf TAGATT "%c.tag" CLIENT and \
         , compare MINATT "=" "true" \
         , substitute FOCUS "tags.focus.name" compare TAGATT "=" FOCUS \
         , set_attr ISMINATT true \
         , set_attr MINATT false \
   . and \
     , compare ISMINATT "=" false \
     , set_attr clients.focus.minimized true

# minimize the focused window
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
```

**Comment by blarz** [comment]
I didn't think of un-minimizing via shortcuts when I created that PR, as I use xfce4 panel for that.
Let's see what Thorsten thinks. Maybe it is better to have it not in by default?

**Comment by t-wissmann** [comment]
Sorry for not reacting earlier. I think it's a good idea to have 'unminimize' available via keys. I use the window switcher `rofi` and my panel (lxpanel) for it.

I like the first solution, because it's short and shows a bit the functionality of the object tree. I think it's fine to show a bit of this in the default autostart. In my opinion, the best solution would be the unminimization of one window (e.g. the last minimized or the longest minimized window), but I think it's feasible with the hlwm commands at the moment.

I'm not sure how usable the second solution is. If one only uses `$Mod-m`, then one can have at most one window minimized (per tag).

We have `$Mod-Shift-m` for minimization in the default autostart. So maybe `$Mod-Ctrl-m` can be used. (I'd like to save `$Mod-m` for maximization)

**Comment by apm256** [comment]
> In my opinion, the best solution would be the unminimization of one window (e.g. the last minimized or the longest minimized window), but I think it's feasible with the hlwm commands at the moment.

I agree with that but, indeed, It doesn't seem possible without an external script!

**Comment by blarz** [comment]
Thanks for the PR @apm256! Should we close this issue?
