### ISSUE TITLE
[BUG] Semi-transparent borders with picom

### ISSUE THREAD

**Issue by Barbarossa93** [herbstluftwm/herbstluftwm#1173]
To continue from [here](https://github.com/herbstluftwm/herbstluftwm/issues/992), there is currently an issue with certain windows that have a depth of 32bit causing the borders to appear semi-transparent when picom is running. Programs affected by this are zathura, vte-based terminals such as termite, and likely others. According to this [picom](https://github.com/yshui/picom/issues/285) issue, this problem is caused by the window manager not specifying a premultiplied value for the border color. For example, dwm applied with the alpha patch appears to fix the problem. However, it's not clear if this is indeed a problem with the window manager or with intel drivers as discussed [here](https://github.com/yshui/picom/issues/586). Interestingly, testing between urxvt with depth 24 and 32, there is no problem, suggesting that it's entirely possible this is an intrinsic problem in vte-based terminals, zathura, and/or picom.

Sorry to pester you @t-wissmann, but have you had a chance to figure out what the dwm alpha patch is doing?

EDIT:
Removing `xf86-video-intel` (the 2D acceleration Xorg intel drivers) on arch linux made no difference. I suppose this could still mean that its a problem with intel, but I have a hunch that it's less likely to be so

**Comment by t-wissmann** [comment]
The PR #1178 fixes the issue on my system with intel graphics.⎄ If you compile from source, you can also manually insert `| (0xffu << 24)` after the two occurrences of `xcol.pixel` (but before the `;`) in `src/decoration.cpp`

**Comment by Barbarossa93** [comment]
:tada: :tada: :tada: Woohoo!!! :tada: :tada: :tada:
That works!! Thank you so much, this bug was driving me crazy!

**Comment by bklaase** [comment]
Thank you for this fix! I had kind of learned to live with it, but still happy it is revolved. After all, more control over the window borders, is (part of) why hlwm is so great!

**Comment by bklaase** [comment]
Not sure yet whether to open a new issue, but I *think* it happened because of this fix;
video artifacts happen when switching to monitors with transparent windows. Or at perhaps 32 bit windows? happens with Zathura too for example. It's difficult to capture as a screenshot, but this happens:

![image](https://user-images.githubusercontent.com/8513117/113449893-1a2c8180-93ff-11eb-9e20-e6357a6de551.png)

for only a fraction of a second. It didn't happen in 9.2.0. 

reproduce by having zathura or termite, etc on a tag. switch to another and press and hold the shortcut to alternate between them. You'll spot it easilly. I checked and this is independent of compositor (even when not running any)

**Comment by t-wissmann** [comment]
I see something similar on the decorations from time to time. Can you open another issue for it?
