### ISSUE TITLE
flickering when cycling between layouts

### ISSUE THREAD

**Issue by sje30** [herbstluftwm/herbstluftwm#1284]
hi again,
is there anything I can do to reduce flickering when I cycle between different layouts?  e.g. if I have four terminals open in one container, and then press Mod-space to cycle between the different layouts there is a flicker (slightly more so than similar operation in other wm's).

Should I use a compositor?  So far, I've just got the standard config; this is with manjaro linux running the -git version from AUR, on a T480S thinkpad.

p.s. where's the best place for asking questions like this?

**Comment by t-wissmann** [comment]
Using a compositor (e.g. picom or compton) will definitely help. Which terminal are you using?

**Comment by sje30** [comment]
xfce4-terminal (but just using that as an example; I get flicker with browser and emacs).
excuse my ignorance, but how do I use a compositor?

**Comment by t-wissmann** [comment]
Just install the compositor (e.g. picom) and then start `picom &` in your `.xinitrc` or manually from a terminal (the `&` is crucial). The `.xinitrc` only works if you start hlwm via the xinitrc (and there, you should add `picom&` before `exec herbstluftwm` line). For testing it, you can also run `picom&` manually from a terminal. (Warning: don't type <kbd>Ctrl+Z</kbd> if you accidentally start `picom` in the foreground, because otherwise X rendering is paused)

**Comment by sje30** [comment]
Thanks.  I tried this with a bare config file though, and its still flickering a bit.  I don't want to waste your time trying to debug this!  Thanks for rapid replies.
