### ISSUE TITLE
No border around alttab-window

### ISSUE THREAD

**Issue by astier** [herbstluftwm/herbstluftwm#1361]
Hi. I am trying to use [alttab](https://github.com/sagb/alttab) together with hlwm. For some reason hlwm isn't drawing a border around the alttab-window. How can I make hlwm draw a border around it? Thank you.

**Comment by t-wissmann** [comment]
It's not possible because hlwm does not even recognize alttab's window because it's created with the window attribute `override_redirect`, see [gui.c line 512](https://github.com/sagb/alttab/blob/1c0754e6d2da346a08b06725ba716350553edf48/src/gui.c#L511).

Also, it makes perfect sense for alttab to mark the window as `override_redirect`, because it is not an application window, but a menu window (similar to a context menu, which also should not be decorated).

Thanks for asking about alttab, I wasn't aware of this tool before!

**Comment by astier** [comment]
Thank you for the explanation. I will implement options in alttab which allow to configure the alttab-border.
