### ISSUE TITLE
Can't i run a tiling window manager in herbstluftwm?

### ISSUE THREAD

**Issue by plus9a** [herbstluftwm/herbstluftwm#1364]
Can't i run a tiling window manager in herbstluftwm?

I seen some articles that saying this wm can start floating everything but can't float single item. Is it true 🥺

**Comment by t-wissmann** [comment]
`hc tilda clients.focus.floating toggle` does not make sense because `tilda` is not a hlwm command.

What you need to do is:

1. put the the above mentioned command in your autostart
2. press Mod4-Shift-f for the windows you want in floating

If you want to auto-float all tilda clients, then put the following in your autostart:
```
hc rule class=Tilda floating=on
```
Note that tilda does not work properly in herbstluftwm.

The cons-list on slant is outdated. The first 'con' about single window floating is wrong since 0.8.0 (April 2020).
