### ISSUE TITLE
Question: How does Herbstluft handle drag and drop?

### ISSUE THREAD

**Issue by codic12** [herbstluftwm/herbstluftwm#1376]
Hi, this isn't really related to the WM development and so probably will be closed, but it's as good as place as any to ask, here goes...

I am writing a WM and I reparent two windows to frame windows, then I can't drag from one window to another; how can I enable this? Window managers like HerbstluftWM manage to do it perfectly. I understand that when I drag out something and drop it on the other window it probably detects that it doesn't support dropping to, but I want to drop to the child window. I can't find relevant code in the WM, so how can I handle this?

Thanks for any answers I might get!

**Comment by t-wissmann** [comment]
Hi, I'm not sure what you mean by 'frame', but I'm trying to explain a bit how window dragging works in hlwm.

Hlwm reparents client windows to a decoration window, and those decoration windows are placed above containers windows (that's hlwm's tiling method). those containers are called "frame" in hlwm, so I'm not sure whether the 'frames' mentioned by you refer to decoration windows or to logical tiling containers:
* clients are reparented into decoration windows
* the decoration windows are placed above container windows, such that it looks as if they were inside the containers (but no reparenting is used here).

When a floating client should be dragged, then the `XMainLoop` grabs the mouse pointer (`XGrabPointer()` in `XMainLoop::draggedClientChanges()`), which then tells the X11 server to send all pointer movement as events to hlwm. This is then used to move the window.

In X, it is not possible to just "move" a window out of it's parent window. Instead, one would need to reparent a window to the root window, do the drag&drop movement and then reparent the window again to it's new parent once the drag&drop is over (e.g. because the mouse button is released).

Does this help?

**Comment by codic12** [comment]
Thanks for the reply!

I was referring to the decorations, sorry, I didn't know that terminology. My question was not about moving the client; I've implemented that long ago. My question was about two clients dragging things to each other. For example, if I open two thunar windows and drag a file from one to the other.

My suspicion is that what needs to happen is that I need to copy a bunch of attributes from the client to the frame window (At least Xdnd scans the window you "drop" the target on for some attribute, I guess Motif does this too). A simple WM which only handles ButtonPress, ButtonRelease, MotionNotify, MapRequest (which reparents), and ConfigureRequest can't handle this.

I can't find anything at all specifically about drag and drop in herbstluftwm, but in general does it do any copying of attributes other than depth and colormap from the client to the parent decoration? If so, where?

**Comment by t-wissmann** [comment]
Ah, regarding actual drag and drop, nothing needs to be implemented on the WM side. So I don't know what is wrong in your software.

**Comment by codic12** [comment]
I think it's just copying properties to decoration window; I'll take a look at the relevant handlers in how herbstluft does it. Thanks!
