### ISSUE TITLE
Titles of non-focused windows in max layout bleeds into focused window's border

### ISSUE THREAD

**Issue by gravndal** [herbstluftwm/herbstluftwm#1388]
See the `p` in `desktop` in this screenshot:
![2021-12-03-04:21:59](https://user-images.githubusercontent.com/4656860/144539810-435a5d1c-e4f5-4942-acd5-846a347509a8.png)

Or the much more noticeable `g`s in this screenshot:
![2021-12-03-04:44:10](https://user-images.githubusercontent.com/4656860/144541780-631d2e49-3bb7-498f-af64-392aa6144836.png)

Relevant settings:
```
$ herbstclient attr theme.
    inner_color/inner_width
          ╻        outer_color/outer_width
          │                  ╻
          │                  │
    ┌────╴│╶─────────────────┷─────┐ ⎫ border_width
    │     │      color             │ ⎬ + title_height
    │  ┌──┷─────────────────────┐  │ ⎭ + padding_top
    │  │====================....│  │
    │  │== window content ==....│  │
    │  │====================..╾──────── background_color
    │  │........................│  │
    │  └────────────────────────┘  │ ⎱ border_width +
    └──────────────────────────────┘ ⎰ padding_bottom

Setting an attribute of the theme object just propagates the value to the respective attribute of the +tiling+ and the +floating+ object.

7 children:
  active.
  floating.
  fullscreen.
  minimal.
  normal.
  tiling.
  urgent.
16 attributes:
 .---- type
 | .-- writable
 | | .-- hookable
 V V V
 c w h background_color = #1a1b1b
 u w h border_width = 3
 c w h color = #000000
 c w h inner_color = #000000
 u w h inner_width = 1
 c w h outer_color = #000000
 u w h outer_width = 1
 u w h padding_bottom = 0
 u w h padding_left = 0
 u w h padding_right = 0
 u w h padding_top = 0
 s w - reset = "Writing this resets all attributes to a default value"
 b w h tight_decoration = false
 c w h title_color = #000000
 f w h title_font = Source Code Pro:size=7:semibold
 u w h title_height = 12
$ herbstclient attr theme.active.color
#a89984
$ herbstclient attr theme.normal.color
#504945
```

A workaround is setting `padding_top` to some fitting number in relation to `(border|inner|outer)_width`: `2` in this case. Though I'd rather have some (slightly) ugly titles than unnecessary imbalanced padding.

**Comment by gravndal** [comment]
As an aside, two features that would be useful with this tabbed layout:
* Specific theming for windows in max-layout frames, e.g. `theme.max.title_height` enabling showing titles only for windows in max layout frames.
* Focus shifting with `focus left/right`.

**Comment by t-wissmann** [comment]
I'm planning to add also an attribute `title_depth` that adds space below the baseline. But for the time being, you can work around this issue by increasing `padding_top`: you won't see the unbalanced padding because window titles are always on or always off at the moment.

There were already multiple requests to show tabs only in some scenarios. I'm not yet sure what's the best way to implement it. I originally intended to implement something like a `title_when` attribute (whose value is one of `always`, `never`, `at_least_one_tab` (i.e. only in max layout), `at_least_two_tabs`).

For focus shifting, you can use `cycle -1`/`cycle +1`. I don't want to change the behaviour of `focus left` because otherwise you have to go through all tabs in order to reach the neighbouring frame.
