### ISSUE TITLE
Piping output of maim to xclip does not work on keybind

### ISSUE THREAD

**Issue by TriedAngle** [herbstluftwm/herbstluftwm#1471]
The maim command gets executed normally (tested without the piping / xclip), the piping to xclip feels ignored but I'm unsure what happens internally.
Command / Key bind in question: `hc keybind $Mod-p spawn maim -s | xclip -selection clipboard -t image/png`
The command works normally when executed from terminal.
I'm using the newest herbstluft, xclip and maim available in pacman / arch

**Comment by t-wissmann** [comment]
The first argument to `|` in your example is `hc keybind $Mod-p spawn maim -s`, this is why it does not work. The following autostart line fixes it:
```bash
hc keybind $Mod-p spawn bash -c \
   "sleep 0.1 ; maim -s | xclip -selection clipboard -t image/png"
```
Also, I recommend passing `--hidecursor` to `maim` because otherwise, the mouse cursor might end up in the screenshots.

The `sleep 0.1` provides a little extra time for releasing the key (there are issues with some select+screenshot tools if a key is still pressed down)

**Comment by t-wissmann** [comment]
(and of course the ugly `sleep 0.1` can be removed and replaced with `Release-$Mod-p` as soon as #1446 is merged)

**Comment by TriedAngle** [comment]
oh I see thanks for explanation :+1:, I will close this then.
