### ISSUE TITLE
Panel  detection erroneously triggered by electron apps 

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#1475]
@The-Compiler reported that https://github.com/IsmaelMartinez/teams-for-linux triggers the panel detection.

**Comment by The-Compiler** [comment]
It definitely has something to do with the system tray icons in trayer/barpyrus, because inserting/removing a microSD card makes my windows jiggle:

https://user-images.githubusercontent.com/625793/184947894-4359b586-2c20-4e78-9619-295e5a9090eb.mp4

Even after setting `auto_detect_panels` to true again, I couldn't reproduce those gaps sticking around however - which is something which even with the Electron apps, never happened deterministically.

**Comment by t-wissmann** [comment]
Is it fixed with #1521?
