### ISSUE TITLE
Tray for panel.sh

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#23]
Many people want a tray, but like the default `panel.sh` otherwise. We should provide some option to add a `stalone`/`trayer` with `panel.sh`.

**Comment by t-wissmann** [comment]
Since we have [barpyrus](https://github.com/t-wissmann/barpyrus) now, I think it does not make sense to put more effort in panel.sh. And of course baryprus now has a support for stalonetray (and trayer).


[![image](https://user-images.githubusercontent.com/9048813/143689969-e92fe9ab-9390-4726-bed2-b80192f591e3.png)](https://user-images.githubusercontent.com/9048813/143689969-e92fe9ab-9390-4726-bed2-b80192f591e3.png)
