### ISSUE TITLE
Reopen window at its original position

### ISSUE THREAD

**Issue by dkrikun** [herbstluftwm/herbstluftwm#376]
I have an application showing a window started via `entr` (waits for a file change, then restarts an application), for example:
```
echo picture.png | entr -r feh picture.png
```

When I initially run the command, the window (of `feh`) is opened in a certain frame of my choice, and I have the ability to move/resize it a I see fit.

The problem arises when the `picture.png` file has been changed, and `entr` restarts `feh`. Wheh `feh` is restarted its window appears in the frame currently focused, whereas I would like it to reappear at the exactly same frame it was positioned in the first place, and preferably in the same layout (e.g. pseudotile).

I have tried to come up with some kind of a rule, but I got stuck because I have no idea how to get the window current monitor, tag, frame and other properties to save them for having been applied after restart.

**Comment by t-wissmann** [comment]
I think this is quite difficult. The main examples on http://eradman.com/entrproject/ are non-interactive/non-gui applications and programs that tell a gui application to reload. In your case, does the following solve the issue?

1. start feh with the same image twice and save its PID: `feh picture.png picture.png & pid=$!`
2. force `feh` reload if `picture.png` changes:
```
echo picture.png | entr -s "kill -USR1 $pid ; kill -USR2 $pid"
```
Unfortunately, I could not find out how to reload an image in feh, that's why I'm forcing at two images in feh's image list. Then I can switch to the previous image (by sending `SIGUSR1`) and then switching to the next image immediately to force the reload.

If pass multiple images to feh anyway, you don't need to duplicate `picture.png`. And if you use feh to display various images for a certain time, you can pass all images to feh directly and then you only need to send `SIGUSR1` in order to request the next image.

**Comment by dkrikun** [comment]
Thank you for your solution.

I guess it would be possible also to send the 'r' keypress to make feh
reload the image.

**Comment by t-wissmann** [comment]
This might work as well. However often, faking key presses does not work for applications that are not focused. See also the `SENDEVENT NOTES` section in the man page of `xdotool`.

**Comment by dkrikun** [comment]
Ok, thanks, I think this can be closed now.
Btw, I am thinking to use `ffmpeg` to read images from pipe as if they were frames -- could work too.
