### ISSUE TITLE
Moving window to focused tag not (always) in view on tag

### ISSUE THREAD

**Issue by sdothum** [herbstluftwm/herbstluftwm#38]
I implemented a simple hide window function which simply moves the focused window to (tick) 'tag

Subsequently restoring the pseudo hidden window from 'tag to the tag in focus with

herbstclient chain . lock . use "'$tag" . move $tag . use $tag . unlock

occaisionally results in the "restored" window not in view. Clicking the mouse in the resulting empty window region, focuses the window into view. This doesn't happen all the time and appears to be tied to ncurses terminal apps and the last remaining window moved from 'tag (though, I haven't run enough scenarios to be 100% certain it's always the last remaining window).

The problem is solved simply by **bring**ing the window instead with:

herbstclient chain . lock . use "'$tag"
winid=$(herbstclient attr clients.focus | grep 's - winid' | cut -d'"' -f2)
herbstclient chain . use $tag . bring $winid . unlock

Not sure if this is a bug or not (I would think the window should at least be in view). As reported, MOST of the time, the moved window to the tag in focus, was visible and had focus (without the raise command). Bring made this 100% reliable.

**Comment by t-wissmann** [comment]
Sorry for not replying earlier, this somehow got lost in the amount of issues here.

Hm difficult to tell what's the issue here. But I think this issue can be closed now, because hlwm now supports window minimization directly (you can run `hc attr clients.focus.minimized true` to minimize a client). If there is still some issue, feel free to re-open this issue or to create another one :-)
