### ISSUE TITLE
focus_follows_mouse not working if empty frame selected

### ISSUE THREAD

**Issue by Nairou** [herbstluftwm/herbstluftwm#568]
I have focus_follows_mouse enabled, which works as expected when going from one window to another. However, if you close the active window, leaving you with an active but empty frame, focus will no longer follow the mouse to another window. You have to click on another window to move focus, to get mouse following working again.

**Comment by fmarczew** [comment]
Hello,

i am also missing the focus on empty frames.
Also kind of related to empty frames:

It would be awesome if there is an option for prefering or prioritize empty frames on placing new windows on the current workspace over splitting the current selcted frame. 

I know this behaviour can be somehow scripted with some chaining of bash scripts like mentioned [here](http://thedarnedestthing.com/hooked%20on%20herbstluftwm)

Are there any plans for Winterbreeze including this ?

Thanks

Best 

Frank

**Comment by t-wissmann** [comment]
In the current git version, the issue raised by @Nairou is fixed.

Another issue raised by @fmarczew:
Focus-follows-mouse towards an empty frame does not work yet, but I'm open for this feature (but it's not high priority). The main task here is to get the right events from the X window system to accomplish this task. (see separate issue #711).

The third issue mentioned here can be implemented quite easily.. (I've added a separate issue for it #710)

Since the actual issue has been resolved, I'm closing this thread.

**Comment by t-wissmann** [comment]
> It would be awesome if there is an option for prefering or prioritize empty frames on placing new windows on the current workspace over splitting the current selcted frame.

In the current git version, you can add
```
hc rule index=e
```
to your autostart, and then new windows will be placed into empty frames.

**Comment by fmarczew** [comment]
Thanks for the quick response will test it out. 

Best

Frank
