### ISSUE TITLE
Positioning windows on configure requests should be monitor-relative

### ISSUE THREAD

**Issue by dnnr** [herbstluftwm/herbstluftwm#576]
It seems that this was fixed in master (https://github.com/herbstluftwm/herbstluftwm/commit/ebed05c0a3faeed9084bb8355532b4f5cfbf2ca6), but still occurs in winterbreeze.

**Comment by preisi** [comment]
I have ported the respective commit to my hlwm fork. However, I would like to verify its correctness before sending a pull request. 
Is there any way to easily test the behaviour of my changes?

**Comment by t-wissmann** [comment]
Great, thanks!

You can run
```
xterm -geometry 50x10+2000+0
```
where the 2000 is some X-coordinate on a monitor on the right. And then the xterm should appear at a reasonable coordinate and not stick on the right edge of the monitor.

**Comment by t-wissmann** [comment]
If you have an application that remembers its coordinates, then you can open and close and open it again. For every monitor, the application should re-appear at roughly the same coordinate (and in particular should not open at the right edge of the monitor).

For example, sonata is an application that saves and restores the window coordinates.

**Comment by t-wissmann** [comment]
The above mentioned commit is not the only commit that implements the geometry-fixing. Most of the work is done by 9e7538f83eccfe0a5cad1bfd7da82e37e1590a76.

**Comment by t-wissmann** [comment]
As it turns out I was wrong with all my comments above:
This Issue (and the commit ebed05c) is about re-interpreting the coordinates on a configure request of an existing client.

My comments (both about the `xterm`-command and the referenced 9e7538f) are about re-interpreting the requested coordinates of a *new* client window when it shows up for the first time. (and the latter issue is now implemented by #614 )

**Comment by t-wissmann** [comment]
Solved by #615.
