### ISSUE TITLE
[Winterbreeze] Frame does not fill entire screen after removing subframe

### ISSUE THREAD

**Issue by cnotis82** [herbstluftwm/herbstluftwm#597]
Steps to reproduce:
1) Initial frame(without clients) is split in 2 subframes
2) Remove one of subframes, the remaining frame does not fill entire screen.

**Comment by blarz** [comment]
I can reproduce this. The remaining frame has a gap on the right and on the bottom.
Switching to another tag and back fixes this.

**Comment by t-wissmann** [comment]
With the default autostart, I can reproduce it too!

**Comment by t-wissmann** [comment]
It only appears with `smart_frame_surroundings` enabled.

**Comment by blarz** [comment]
I think the problem lies in src/framedecoration.cpp.
`if (settings->smart_frame_surroundings() && !data.hasParent) { bw = 0;}`

The `data.hasParent` check maybe wrong.
If I understand `FrameTree::removeFrameCommand()` correctly,
in case we remove the second to last frame, the last frame becomes the new `root_` like this:
`root_ = newparent;`
Isn't the parent of `newparent` still referencing `root_`?

Not sure if that is the actual problem, I really don't know the code that good (nor do I understand weak and smart pointers fully to be honest).

**Comment by t-wissmann** [comment]
Yes, this was the issue and @blarz fixed it in PR #678.
