### ISSUE TITLE
wselect.sh script is not compatible with scratchpad and similar scripts

### ISSUE THREAD

**Issue by neg-serg** [herbstluftwm/herbstluftwm#76]
It seems that wselect script, which is EWHM-based as I seen is not compatible with scratchpad or probably all kind of hidden displays.

Steps to reproduce:

1) Create a scratchpad with scratchpad.sh or something like this
2) Add some window to it, for example st, urxvt...
3) Hide scratchpad
4) Try to select it with wselect.sh

You will get this window fullscreen, while only monitor with window should be selected.

Maybe it is not a bug, I simply do something wrong, but it looks very annoying.

I just want to bring my old notion functionality to herbstluftwm, because I've tried to support notion(a bunch of magic pain drive developement style code). Tree-based scratchpads is one of it. By the way I did offer this feature in IRC several years ago, it's bad that this not works well yet.

**Comment by t-wissmann** [comment]
That's very difficult to solve (if it's a bug at all), because `wselect.sh` can not know that the `scratchpad` tag is usually shown on a dedicated monitor created by some other script. And even if it did know, it still didn't know how to call this script. The only solution I see is to create an optional attribute for every tag, saying _if this attribute is set, then don't focus me directly but call the following command instead_.

Right now, you can already implement that by tweaking `wselect.sh` and `scratchpad.sh` to respect such an attribute. (Note that you can add arbitrary `my_`... attributes to any kind of object).
