### ISSUE TITLE
"repeat" command [Feature Request]

### ISSUE THREAD

**Issue by blairdrummond** [herbstluftwm/herbstluftwm#84]
I was wondering if a command like `repeat [delimiter] [count] [delimiter] [action]` could be implemented? Here's a case where it could be useful. Suppose I want to pseudotile everything on a tag:

```
herbstclient and \
 . compare tags.focus.client_count ge 1  . pseudotile . cycle +1 \
 . compare tags.focus.client_count ge 2  . pseudotile . cycle +1 \
 . compare tags.focus.client_count ge 3  . pseudotile . cycle +1 \
 . compare tags.focus.client_count ge 4  . pseudotile . cycle +1 # continued
```

But it would be nice if instead one could do

```
herbstclient substitute \
    COUNT \
    tags.focus.client_count \
    repeat \
    . COUNT \
    . chain \
        , pseudotile \
        , cycle +1
```

**Comment by t-wissmann** [comment]
In principle one can imagine implementing something like `repeat`. However in your case (and in most cases), some `foreach` 'client' `on` 'tag' seems to be more appropriate. Right now, the development in master is quite stale because of the slowly developing winterbreeze branch, so it might take a while. But you can implement the `foreach`-loop manually in bash, and still, `herbstclient` is called only twice regardless of the window count:
```bash
#!/bin/bash
# get all the clients out there
clients=( $(herbstclient complete 1 attr clients.|grep -oE '0x[^.]*') )
# successively build up a chain of commands. Each of them needs the current tag name,
# so get that once for all:
cmd=( substitute TAG tags.focus.name chain )
for c in "${clients[@]}" ; do
    # for a client c
    cmd+=(
        . and
           # if its on the current tag
          .. compare clients.$c.tag = TAG
          # then toggle its pseudotile state
          .. set_attr clients.$c.pseudotile toggle
    )
done
herbstclient "${cmd[@]}"
```

**Comment by t-wissmann** [comment]
With the new features in the git branch, one can do the following:
```bash

pseudotileall=(
    foreach C clients.
        substitute TAG tags.focus.name
        sprintf ATTR '%c.pseudotile' C
        sprintf CTAGATTR '%c.tag' C  # the client's tag attribute
        and . compare CTAGATTR = TAG
            . echo setting ATTR to true # only debug output
            . set_attr ATTR true
)
herbstclient "${pseudotileall[@]}"
```

On a tag with two clients, the output is:
```
setting clients.0x3a0000a.pseudotile to true
setting clients.0x440000a.pseudotile to true
setting clients.focus.pseudotile to true
```

Unfortunately, `toggle` does not work here, because the `set_attr` is issued twice: once for the window id and again for the `clients.focus`.

The array variable only exists to improve readability, so you can also create a keybinding for it:
```
herbstclient keybind Mod4-p "${pseudotileall[@]}"
```

By the way, herbstluftwm now supports single-window floating. Maybe this solves the original issue you were trying to solve.

**Comment by t-wissmann** [comment]
I think everything here has been implemented (with `foreach` being more convenient than a plain integer-based `repeat` loop), so we can close this. Please re-open if I missed something.
