### ISSUE TITLE
Conceptual similarities between attributes and settings. Why do we have both?

### ISSUE THREAD

**Issue by wtok** [herbstluftwm/herbstluftwm#95]
It bugs me a little that we have both attributes and settings, where attributes are just like settings, except with more features.

Why not move all settings (`herbstclient set ...`) into an attribute class, say, an `hlwm` class.

So `hc set default_frame_layout 1` would become `hc attr hlwm.default_frame_layout 1`. All the `settings` code could be deleted, and the man page would get shorter.

What's the reasoning behind having both?

**Comment by The-Compiler** [comment]
Mainly that settings were there before attributes were added :wink:

IIRC the winterbreeze rewrite branch has some ideas about unifying them though.

**Comment by t-wissmann** [comment]
As florian pointed out, settings are older and only remain for compatibility. And the `hlwm` object you proposed already exists, it is called `settings.`:

```
$ herbstclient attr settings.
0 children.
43 attributes:
 .---- type
 | .-- writeable
 V V
 i w verbose              = 0
 i w frame_gap            = 8
 i w frame_padding        = 0
 i w window_gap           = 0
 i w snap_distance        = 10
 i w snap_gap             = 8
 i w mouse_recenter_gap   = 0
 s w frame_border_active_color = "#222222"
 s w frame_border_normal_color = "#101010"
 s w frame_border_inner_color = "black"
 s w frame_bg_normal_color = "#303030"
 s w frame_bg_active_color = "#809220"
 i w frame_bg_transparent = 1
 i w frame_transparent_width = 4
 i w frame_border_width   = 1
 i w frame_border_inner_width = 0
 i w frame_active_opacity = 100
 i w frame_normal_opacity = 100
 i w focus_crosses_monitor_boundaries = 1
 i w always_show_frame    = 0
 i w default_direction_external_only = 0
 i w default_frame_layout = 0
 i w focus_follows_mouse  = 1
 i w focus_stealing_prevention = 1
 i w swap_monitors_to_get_tag = 1
 i w raise_on_focus       = 0
 i w raise_on_focus_temporarily = 0
 i w raise_on_click       = 1
 i w gapless_grid         = 1
 i w smart_frame_surroundings = 0
 i w smart_window_surroundings = 0
 i w monitors_locked      = 0
 i w auto_detect_monitors = 0
 i w pseudotile_center_threshold = 10
 i w update_dragged_clients = 0
 s w tree_style           = "╾│ ├╰╼─╮"
 s w wmname               = "herbstluftwm"
 s w window_border_width  = 3
 s w window_border_inner_width = 1
 s w window_border_inner_color = #101010
 s w window_border_active_color = #9fbc00
 s w window_border_normal_color = #454545
 s w window_border_urgent_color = #C71364
```

Technically in `master`, the settings-object is a wrapper for the old settings code. In the winterbreeze branch, it will be the other way around and the settings interface will be a wrapper for the attributes of the `settings` object. It is still work in progress, but you can already take a look at it: [settings.h](https://github.com/herbstluftwm/herbstluftwm/blob/winterbreeze/src/settings.h) /  [settings.cpp](https://github.com/herbstluftwm/herbstluftwm/blob/winterbreeze/src/settings.cpp) (Right now, there is still the old settings code in settings.cpp, but it will disappear soon)

**Comment by wtok** [comment]
Sweet, sounds like a step in the right direction.

Still though, why keep settings around in winterbreeze? The code will get simpler, but users will still have to understand two systems for the same thing -- just now one will be imaginary.

Also, when will winterbreeze be done, feature-wise? I can't find any documentation of what it actually intends to change -- just some issues are randomly tagged "winterbreeze". If I wanted to help out with getting winterbreeze merged to master, where would I start?

**Comment by ypnos** [comment]
Hello wtok, as impatient we all may be regarding cleaner interfaces and new features, right now the goal is for winterbreeze to be as backwards-compatible as possible from the user perspective. This doesn't mean new users have to use the settings commands, instead they can operate on the settings object as you suggested. The manpage can be worded accordingly.

I think staying backwards-compatible right now is reasonable because it is harder to change "everything" at the same time and do it right. We should not run into the situations where users have to choose between old and new hlwm because the new version is not working right for them. Existing users should be on board from day 1.

One of the anticipated new features are per-window/per-frame decoration setting. There are several possible ways to do this and this will also lead to different interfaces for the user. It might be questionable to change the interface for these settings right now just for the sake of consistency and then change it yet again in the near future (where, e.g. we would have several theme objects and a theme name attributes for each window/frame). 

 believe most issues tagged "winterbreeze" can be seen as "will not be done before winterbreeze" rather than "will be part of first winterbreeze release". So winterbreeze is "done" when it has feature-parity with master. At the current stage I think you might help most with testing (this includes writing automated tests) and ironing out bugs, but you should ask Thorsten what can be tested right now.

**Comment by t-wissmann** [comment]
Apart from compatibility, there are two further reasons for keeping the settings:

1) For new users, it's easier to have one central place with the core options (like border color, or the focus_follows_mouse setting) than to search through the entire object_tree.

2) For some settings, it's not easy to find a object holding them. E.g. swap_monitors_to_get_tag could go to both the monitors and the tags object. But in my opinion it's a 'core option', and so fits well to this 'central settings object'.

**Comment by t-wissmann** [comment]
The initial question and the subsequent questions seem to be answered, so I'm closing this issue.
